/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ListRoom;
import Model.Room;
import Model.User;
import Service.UserService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class AddUserScreen extends javax.swing.JFrame {

    UserService userService;
    private javax.swing.JTable tableUsState_thanhHung155;
    private javax.swing.JLabel totalUser_thanhHung155 ;
    private ArrayList<User> cloneArrUser_thanhHung155 ;
    /**
     * Creates new form Add2
     */
    
    public DefaultTableModel getModelTable() {
        DefaultTableModel model = (DefaultTableModel) tableUsState_thanhHung155.getModel();
        return model;
    }

    public void setTable(ArrayList<User> list) {
        getModelTable().getDataVector().removeAllElements();
        list.forEach((user) -> {
            getModelTable().addRow(new Object[]{user.getUserId() , user.getFirstName() + user.getLastName() ,user.getEmail() , user.getPhoneNumber() });
        });
    }
    
    public AddUserScreen(javax.swing.JTable table , ArrayList<User> listUser , javax.swing.JLabel labelTotal) {
        initComponents();
        tableUsState_thanhHung155 = table ; 
        cloneArrUser_thanhHung155 = listUser ;
        totalUser_thanhHung155 = labelTotal ;
        userService = new UserService();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bt_Add_khoa15 = new javax.swing.JButton();
        Bt_Black_khoa15 = new javax.swing.JButton();
        lastName_khoa15 = new javax.swing.JTextField();
        email_khoa15 = new javax.swing.JTextField();
        firstName_khoa15 = new javax.swing.JTextField();
        phone_khoa15 = new javax.swing.JTextField();
        pass_khoa15 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 199, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 139, 214));
        jLabel1.setText("Create new user");

        Bt_Add_khoa15.setBackground(new java.awt.Color(131, 184, 255));
        Bt_Add_khoa15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bt_Add_khoa15.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Add_khoa15.setText("Add");
        Bt_Add_khoa15.setMaximumSize(new java.awt.Dimension(72, 27));
        Bt_Add_khoa15.setMinimumSize(new java.awt.Dimension(72, 27));
        Bt_Add_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Add_khoa15ActionPerformed(evt);
            }
        });

        Bt_Black_khoa15.setBackground(new java.awt.Color(211, 71, 71));
        Bt_Black_khoa15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bt_Black_khoa15.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Black_khoa15.setText("Back");
        Bt_Black_khoa15.setMaximumSize(new java.awt.Dimension(72, 27));
        Bt_Black_khoa15.setMinimumSize(new java.awt.Dimension(72, 27));
        Bt_Black_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Black_khoa15ActionPerformed(evt);
            }
        });

        lastName_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastName_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "LastName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N

        email_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        email_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_khoa15ActionPerformed(evt);
            }
        });

        firstName_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstName_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        firstName_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_khoa15ActionPerformed(evt);
            }
        });

        phone_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phone_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        phone_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_khoa15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bt_Black_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bt_Add_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email_khoa15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(firstName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastName_khoa15, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                            .addComponent(phone_khoa15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass_khoa15, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phone_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(email_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pass_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Add_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Black_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_Add_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Add_khoa15ActionPerformed
        // TODO add your handling code here:
        userService.addUser(firstName_khoa15.getText(), lastName_khoa15.getText(), phone_khoa15.getText(), email_khoa15.getText(), new String(pass_khoa15.getPassword()));
        JOptionPane.showMessageDialog(null, "Add New User Success", "", JOptionPane.INFORMATION_MESSAGE);
        try {
            cloneArrUser_thanhHung155 = userService.getAllUser();
        } catch (SQLException ex) {
            Logger.getLogger(AddUserScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTable(cloneArrUser_thanhHung155);
        totalUser_thanhHung155.setText(Integer.toString(cloneArrUser_thanhHung155.size()));
        this.setVisible(false);
    }//GEN-LAST:event_Bt_Add_khoa15ActionPerformed

    private void Bt_Black_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Black_khoa15ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Bt_Black_khoa15ActionPerformed

    private void email_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_khoa15ActionPerformed

    private void phone_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_khoa15ActionPerformed

    private void firstName_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_khoa15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add_khoa15;
    private javax.swing.JButton Bt_Black_khoa15;
    private javax.swing.JTextField email_khoa15;
    private javax.swing.JTextField firstName_khoa15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName_khoa15;
    private javax.swing.JPasswordField pass_khoa15;
    private javax.swing.JTextField phone_khoa15;
    // End of variables declaration//GEN-END:variables
}
