/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ListRoom;
import Model.Room;
import Model.User;
import Service.UserService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class AddUserScreen extends javax.swing.JFrame {

    UserService userService;
    private javax.swing.JTable tableUsState_thanhHung155;
    private javax.swing.JLabel totalUser_thanhHung155 ;
    private ArrayList<User> cloneArrUser_thanhHung155 ;
    /**
     * Creates new form Add2
     */
    
    public DefaultTableModel getModelTable() {
        DefaultTableModel model = (DefaultTableModel) tableUsState_thanhHung155.getModel();
        return model;
    }

    public void setTable(ArrayList<User> list) {
        getModelTable().getDataVector().removeAllElements();
        list.forEach((user) -> {
            getModelTable().addRow(new Object[]{user.getUserId() , user.getFirstName() + user.getLastName() ,user.getEmail() , user.getPhoneNumber() });
        });
    }
    
    public AddUserScreen(javax.swing.JTable table , ArrayList<User> listUser , javax.swing.JLabel labelTotal) {
        initComponents();
        tableUsState_thanhHung155 = table ; 
        cloneArrUser_thanhHung155 = listUser ;
        totalUser_thanhHung155 = labelTotal ;
        userService = new UserService();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        email_khoa15 = new javax.swing.JTextField();
        phone_khoa15 = new javax.swing.JTextField();
        firstName_khoa15 = new javax.swing.JTextField();
        lastName_khoa15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pass_khoa15 = new javax.swing.JPasswordField();
        Bt_Black_khoa15 = new javax.swing.JButton();
        Bt_Add_khoa15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(236, 247, 253));

        jPanel1.setBackground(new java.awt.Color(131, 184, 255));
        jPanel1.setForeground(new java.awt.Color(131, 184, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hotel_illu3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        email_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        email_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_khoa15ActionPerformed(evt);
            }
        });

        phone_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phone_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        phone_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_khoa15ActionPerformed(evt);
            }
        });

        firstName_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstName_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        firstName_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_khoa15ActionPerformed(evt);
            }
        });

        lastName_khoa15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastName_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LastName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        lastName_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_khoa15ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 139, 214));
        jLabel1.setText("Create new user");

        pass_khoa15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N

        Bt_Black_khoa15.setBackground(new java.awt.Color(211, 71, 71));
        Bt_Black_khoa15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bt_Black_khoa15.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Black_khoa15.setText("Back");
        Bt_Black_khoa15.setMaximumSize(new java.awt.Dimension(72, 27));
        Bt_Black_khoa15.setMinimumSize(new java.awt.Dimension(72, 27));
        Bt_Black_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Black_khoa15ActionPerformed(evt);
            }
        });

        Bt_Add_khoa15.setBackground(new java.awt.Color(131, 184, 255));
        Bt_Add_khoa15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bt_Add_khoa15.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Add_khoa15.setText("Add");
        Bt_Add_khoa15.setMaximumSize(new java.awt.Dimension(72, 27));
        Bt_Add_khoa15.setMinimumSize(new java.awt.Dimension(72, 27));
        Bt_Add_khoa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Add_khoa15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Bt_Black_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bt_Add_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email_khoa15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(firstName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastName_khoa15))
                            .addComponent(phone_khoa15)
                            .addComponent(pass_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lastName_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Add_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Black_khoa15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_Add_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Add_khoa15ActionPerformed
        // TODO add your handling code here:
        userService.addUser(firstName_khoa15.getText(), lastName_khoa15.getText(), phone_khoa15.getText(), email_khoa15.getText(), new String(pass_khoa15.getPassword()));
        JOptionPane.showMessageDialog(null, "Add New User Success", "", JOptionPane.INFORMATION_MESSAGE);
        try {
            cloneArrUser_thanhHung155 = userService.getAllUser();
        } catch (SQLException ex) {
            Logger.getLogger(AddUserScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTable(cloneArrUser_thanhHung155);
        totalUser_thanhHung155.setText(Integer.toString(cloneArrUser_thanhHung155.size()));
        this.setVisible(false);
    }//GEN-LAST:event_Bt_Add_khoa15ActionPerformed

    private void Bt_Black_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Black_khoa15ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Bt_Black_khoa15ActionPerformed

    private void email_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_khoa15ActionPerformed

    private void phone_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_khoa15ActionPerformed

    private void firstName_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_khoa15ActionPerformed

    private void lastName_khoa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_khoa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_khoa15ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add_khoa15;
    private javax.swing.JButton Bt_Black_khoa15;
    private javax.swing.JTextField email_khoa15;
    private javax.swing.JTextField firstName_khoa15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastName_khoa15;
    private javax.swing.JPasswordField pass_khoa15;
    private javax.swing.JTextField phone_khoa15;
    // End of variables declaration//GEN-END:variables
}
