/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import Service.*;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable ;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author raven
 */
public class BookingRoom extends javax.swing.JFrame {

    private User userBooking_thanhHung155;
    private Room roomBooking_thanhHung155;
    private String reservationDate;
    private UserService userService = new UserService();
    private javax.swing.JTable tableState_thanhHung155;
    private ListRoom lr_thanhHung155 ;
    private RoomsService roomsService = new RoomsService();
    /**
     * Creates new form Main
     */
    public DefaultTableModel getModelTable() {
        DefaultTableModel model = (DefaultTableModel) tableState_thanhHung155.getModel();
        return model;
    }

    public void setTable(ArrayList<Room> list) {
        getModelTable().getDataVector().removeAllElements();
        list.forEach((room) -> {
            getModelTable().addRow(new Object[]{room.getRoomNumber(), room.getRoomType(), room.getRates(), room.getNumberOfBed(), room.isAvainable()});
        });
    }
    
    public BookingRoom(Room room, User user ,javax.swing.JTable table , ListRoom lr) {
        initComponents();
        userBooking_thanhHung155 = user;
        roomBooking_thanhHung155 = room;
        tableState_thanhHung155 = table ;
        lr_thanhHung155 = lr ;
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
        SelectedDate d = dateChooser.getSelectedDate();
        reservationDate = d.getDay() + "-" + d.getMonth() + "-" + d.getYear();
        reservationDate_thanhHung155.setText(reservationDate);
        valueRoomNumber_thanhHung155.setText(Integer.toString(room.getRoomNumber()));
        valueRoomType_thanhHung155.setText(room.getRoomType());
        valueRates_thanhHung155.setText(String.valueOf(room.getRates()));
        valueNumberOfBed_thanhHung155.setText(Integer.toString(room.getNumberOfBed()));

    }

    private BookingRoom() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        jButton5 = new javax.swing.JButton();
        txtDate1 = new javax.swing.JTextField();
        labelRN_thanhHung155 = new javax.swing.JLabel();
        valueRoomNumber_thanhHung155 = new javax.swing.JLabel();
        labelRT_thanhHung155 = new javax.swing.JLabel();
        valueRoomType_thanhHung155 = new javax.swing.JLabel();
        labelRates_thanhHung155 = new javax.swing.JLabel();
        valueRates_thanhHung155 = new javax.swing.JLabel();
        labelNumberOfBed_thanhHung155 = new javax.swing.JLabel();
        valueNumberOfBed_thanhHung155 = new javax.swing.JLabel();
        labelCheckInDate_thanhHung155 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valueNbG_thanhHung155 = new javax.swing.JTextField();
        labelRvD_thanhHung155 = new javax.swing.JLabel();
        reservationDate_thanhHung155 = new javax.swing.JLabel();
        btnBackUserScr_thanhHung155 = new javax.swing.JLabel();
        btnBooking_ThanhHung155 = new javax.swing.JLabel();

        dateChooser.setForeground(new java.awt.Color(97, 155, 231));
        dateChooser.setTextRefernce(txtDate1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        labelRN_thanhHung155.setText("Room Number : ");

        labelRT_thanhHung155.setText("Room Type : ");

        labelRates_thanhHung155.setText("Rates : ");

        labelNumberOfBed_thanhHung155.setText("NumberOfBed : ");

        labelCheckInDate_thanhHung155.setText("Check In Date :");

        jLabel1.setText("Number Of  Guests : ");

        labelRvD_thanhHung155.setText("Reservation Date :");

        btnBackUserScr_thanhHung155.setText("Back");
        btnBackUserScr_thanhHung155.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackUserScr_thanhHung155.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackUserScr_thanhHung155MouseClicked(evt);
            }
        });

        btnBooking_ThanhHung155.setText("Booking");
        btnBooking_ThanhHung155.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBooking_ThanhHung155.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBooking_ThanhHung155MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBooking_ThanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(valueNbG_thanhHung155, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRvD_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationDate_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelCheckInDate_thanhHung155, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelRates_thanhHung155, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRT_thanhHung155, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRN_thanhHung155, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                .addComponent(labelNumberOfBed_thanhHung155)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueNumberOfBed_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueRates_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueRoomNumber_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valueRoomType_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(296, 296, 296)
                                .addComponent(btnBackUserScr_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueRoomNumber_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRN_thanhHung155))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRT_thanhHung155)
                        .addComponent(valueRoomType_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackUserScr_thanhHung155))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRates_thanhHung155)
                    .addComponent(valueRates_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberOfBed_thanhHung155)
                    .addComponent(valueNumberOfBed_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelCheckInDate_thanhHung155)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valueNbG_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRvD_thanhHung155)
                    .addComponent(reservationDate_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBooking_ThanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBackUserScr_thanhHung155MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackUserScr_thanhHung155MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnBackUserScr_thanhHung155MouseClicked

    private void btnBooking_ThanhHung155MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBooking_ThanhHung155MouseClicked
        SelectedDate d = dateChooser.getSelectedDate();
        String checkIn = d.getDay() + "-" + d.getMonth() + "-" + d.getYear();
        try {
            if (valueNbG_thanhHung155.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Maybe you missing field NumberOfGuest^^", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                userService.bookingRom(userBooking_thanhHung155.getUserId(), roomBooking_thanhHung155.getRoomNumber(), checkIn, Integer.parseInt(valueNbG_thanhHung155.getText()), reservationDate);
                lr_thanhHung155.setArrListRoom(roomsService.getAllRooms());
                setTable(lr_thanhHung155.getArrListRoom());
                JOptionPane.showMessageDialog(null, "You have successfully booked your room", "", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(BookingRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBooking_ThanhHung155MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackUserScr_thanhHung155;
    private javax.swing.JLabel btnBooking_ThanhHung155;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCheckInDate_thanhHung155;
    private javax.swing.JLabel labelNumberOfBed_thanhHung155;
    private javax.swing.JLabel labelRN_thanhHung155;
    private javax.swing.JLabel labelRT_thanhHung155;
    private javax.swing.JLabel labelRates_thanhHung155;
    private javax.swing.JLabel labelRvD_thanhHung155;
    private javax.swing.JLabel reservationDate_thanhHung155;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField valueNbG_thanhHung155;
    private javax.swing.JLabel valueNumberOfBed_thanhHung155;
    private javax.swing.JLabel valueRates_thanhHung155;
    private javax.swing.JLabel valueRoomNumber_thanhHung155;
    private javax.swing.JLabel valueRoomType_thanhHung155;
    // End of variables declaration//GEN-END:variables
}
