/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Room;
import Model.ListRoom;
import Service.RoomsService;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kiet
 */
public class RoomManagerScreen extends javax.swing.JPanel {

    private ListRoom arrRoom_TuanKiet05;
    private RoomsService roomService_TuanKiet05 = new RoomsService();

    public DefaultTableModel getModelTable() {
        DefaultTableModel model = (DefaultTableModel) RoomTable_TuanKiet05.getModel();
        return model;
    }

    public void setTable(ArrayList<Room> list) {
        getModelTable().getDataVector().removeAllElements();
        list.forEach((room) -> {
            getModelTable().addRow(new Object[]{room.getRoomNumber(),room.getRoomType(),room.getNumberOfBed(),room.getRates(),room.isAvainable()});
        });

    }

    public RoomManagerScreen() throws SQLException {
        initComponents();
        arrRoom_TuanKiet05 = new ListRoom(roomService_TuanKiet05.getAllRooms());
        setTable(arrRoom_TuanKiet05.getArrListRoom());
 
        RoomTable_TuanKiet05.getTableHeader().setBackground(new Color(131, 184, 255));
        RoomTable_TuanKiet05.getTableHeader().setForeground(new Color(255, 255, 255));
        RoomTable_TuanKiet05.getTableHeader().setPreferredSize(new Dimension(35, 35));
        RoomTable_TuanKiet05.getTableHeader().setFont(new Font("Arial", Font.BOLD, 18));
        totalRoom_thanhHung155.setText(Integer.toString(arrRoom_TuanKiet05.getArrListRoom().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable_TuanKiet05 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SearchInput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        totalRoom_thanhHung155 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 247, 253));

        RoomTable_TuanKiet05.setBackground(new java.awt.Color(255, 255, 255));
        RoomTable_TuanKiet05.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RoomTable_TuanKiet05.setForeground(new java.awt.Color(51, 51, 51));
        RoomTable_TuanKiet05.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RoomNumber", "RoomType", "NumberOfBed", "Rates"
            }
        ));
        RoomTable_TuanKiet05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoomTable_TuanKiet05.setRowHeight(35);
        RoomTable_TuanKiet05.setRowMargin(5);
        jScrollPane1.setViewportView(RoomTable_TuanKiet05);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 139, 214));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room Management");

        SearchInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SearchInput.setForeground(new java.awt.Color(0, 0, 0));
        SearchInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 15), new java.awt.Color(36, 139, 214))); // NOI18N
        SearchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchInputKeyReleased(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(36, 139, 214));
        AddButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add New Room");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(238, 224, 102));
        editButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(211, 71, 71));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Room", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(36, 139, 214))); // NOI18N

        totalRoom_thanhHung155.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        totalRoom_thanhHung155.setForeground(new java.awt.Color(131, 184, 255));
        totalRoom_thanhHung155.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRoom_thanhHung155, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRoom_thanhHung155, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(SearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
                
        AddNewRoomScreen addRoom = new AddNewRoomScreen(RoomTable_TuanKiet05 ,arrRoom_TuanKiet05.getArrListRoom() , totalRoom_thanhHung155);
        addRoom.setVisible(true);
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        int row = RoomTable_TuanKiet05.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(RoomManagerScreen.this, "Chon phong muon xoa", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(RoomManagerScreen.this, "Chac chan muon xoa khong?");
            if (confirm == JOptionPane.YES_OPTION) {
                int roomNumber = Integer.valueOf(String.valueOf(RoomTable_TuanKiet05.getValueAt(row, 0)));
                try {
                    roomService_TuanKiet05.DeleteRoom(roomNumber);
                    arrRoom_TuanKiet05.setArrListRoom(roomService_TuanKiet05.getAllRooms());
                    setTable(arrRoom_TuanKiet05.getArrListRoom());
                    totalRoom_thanhHung155.setText(Integer.toString(arrRoom_TuanKiet05.getArrListRoom().size()));
                } catch (SQLException ex) {
                    Logger.getLogger(RoomManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    public void searchTable(String value) {
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(getModelTable());
        RoomTable_TuanKiet05.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(value));
    }
    private void SearchInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchInputKeyReleased
        searchTable(SearchInput.getText());
    }//GEN-LAST:event_SearchInputKeyReleased

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        
        int row = RoomTable_TuanKiet05.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(RoomManagerScreen.this, "Chon phong muon sua", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int roomNumber = Integer.valueOf(String.valueOf(RoomTable_TuanKiet05.getValueAt(row, 0)));
            
            try {
                Room RoomNeedUpdated = roomService_TuanKiet05.getRoomByRoomNumber(roomNumber);
                UpdateRoom screenUpdate = new UpdateRoom(RoomNeedUpdated , RoomTable_TuanKiet05 , arrRoom_TuanKiet05.getArrListRoom());
                screenUpdate.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(RoomManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTable RoomTable_TuanKiet05;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalRoom_thanhHung155;
    // End of variables declaration//GEN-END:variables
}
